export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";
export const CHECK_CURRENT_USER = "CHECK_CURRENT_USER";
export const LOADING_CURRENT_USER = "LOADING_CURRENT_USER";
